name: Run Linter Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make install-deps

      - name: Run Linters
        run: make lint
